version: '3.2'

services:
  local-db:
    image: mysql:8.0.22
    ports:
      - "3307:3307"
    volumes:
      - ./data/db-data:/var/lib/mysql
      - ./data/db-config:/etc/mysql/conf.d
      - ./data/db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
      TZ: 'Europe/Belgrade'
    restart: on-failure
    container_name: local_db
    networks:
      - cloudnet

  auth-srv:
    image: jboss/keycloak:12.0.4
    ports:
      - "8888:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      TZ: 'Europe/Belgrade'
    restart: on-failure
    container_name: keycloak
    networks:
      - cloudnet

networks:
  cloudnet: